[package]
name = "stm32f4xx-usart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"cortex-m" = "0.7.7"
"cortex-m-rt" = "0.7.3"
"panic-halt" = "0.2.0"
"libm" = "0.2.8"
log = "0.4.22"